version: '3'

services:
  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: agsr
  monitor-sensors:
    build: .
    image: monitor-sensors
    ports:
      - 8080:8080
    depends_on:
      - postgres